# site configuration

# theme: jekyll-theme-gitbook
theme: jekyll-theme-minimal

# Sprache
lang: de-DE

# https://kevinnovak.github.io/Time-Zone-Picker
timezone: Europe/Berlin

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md

# main title
title: GitHub-Website von Regenpfeifer

# used by seo meta and the atom feed
# description: Übersicht

# Logo / Bilddatei
logo: /assets/img/avatar.jpg

# Downloads
show_downloads: false

# webmaster_verifications:
#   google: U9-hCLAR44wY-5vEZSfl8iVgClFj5L0nuUgP8pdl2xo

# Eigene Links
my_links:
  - title: Sudelbuch
    url: https://regenpfeifer.net
  - title: Microblog
    url: https://social.regenpfeifer.net/@charadrius
  - title: Github
    url: https://github.com/regenpfeifer

    
