# site configuration

theme: jekyll-theme-primer
# theme: jekyll-theme-minimal

lang: de

# https://kevinnovak.github.io/Time-Zone-Picker
timezone: Europe/Berlin

# jekyll-seo-tag settings â€º https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md

# main title
title: GitHub-Website von Regenpfeifer

# subtitle
tagline: Blog

# used by seo meta and the atom feed
description: Blog by Regenpfeifer

# protocol & hostname for your site (it does not end with a '/')
url: https://regenpfeifer.github.io

author:
  name: Regenpfeifer
  # sets the `author.url` property. helps Google to disambiguate the correct author of articles
  # url: https://github.com/cgoldberg

github:
  username: regenpfeifer

#twitter:
#  username: cgoldberg

social:
  # displayed as the default author of the posts and the copyright owner in the footer
  name: Regenpfeifer
  #email: example@domain.com
  links:
    # first element serves as the copyright owner's link
    - https://github.com/regenpfeifer

# webmaster_verifications:
#   google: U9-hCLAR44wY-5vEZSfl8iVgClFj5L0nuUgP8pdl2xo

# end of `jekyll-seo-tag` settings


# color scheme setting
# note: empty will follow the system prefer color by default,
# and there will be a toggle to switch the theme between dark
# and light on the bottom left of the sidebar.
# available options: light, dark
theme_mode: dark

# avatar on sidebar (supports local or CORS resources)
# avatar: /assets/img/corey_goldberg.jpg

# global switch for TOC in posts (boolean)
toc: false

